definitions:
  errorDto.DomainError:
    properties:
      domainErrorCode:
        type: integer
      message:
        type: string
    type: object
  errorDto.DomainErrorWrapper:
    properties:
      errors:
        items:
          $ref: '#/definitions/errorDto.DomainError'
        type: array
      statuscode:
        type: integer
      timestamp:
        type: string
    type: object
  registerUserDto.RegisterUserResponse:
    properties:
      country:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      realtor:
        type: boolean
      subscription_id:
        type: string
    type: object
info:
  contact: {}
  description: REST API server for bolig-side aka 'the Feedback' app
  title: bolig-side
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: |-
        DomainErrorCodes:
        2: Email is already in use
        3: Password not secure
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/registerUserDto.RegisterUserResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errorDto.DomainErrorWrapper'
      summary: Registers a user
      tags:
      - Auth
swagger: "2.0"
